apiVersion: v1
kind: Service
metadata:
  name: {{ include "default-http-backend.fullname" . }}
  labels:
    {{- include "default-http-backend.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "default-http-backend.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP