apiVersion: rbac.authorization.k8s.io/v1
# kubernetes versions before 1.8.0 should use rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: get_pods
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list","watch"]

