apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  labels:
    run: jekyll
  namespace: development
spec:
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site
  containers:
  - name: jekyll-site
    image: kodekloud/jekyll-serve
    volumeMounts:
        - mountPath: "/site"
          name: site
  initContainers:
  - name: copy-jekyll-site
    image: kodekloud/jekyll
    command: [ "jekyll", "new", "/site" ]
    volumeMounts:
        - mountPath: "/site"
          name: site

