apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
  name: {{ include "nginx-ingress.fullname" . }}-leader-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
  name: {{ include "nginx-ingress.fullname" . }}-configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-ingress.fullname" . }}-tcp-services
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
  name: {{ include "nginx-ingress.fullname" . }}-udp-services